"""Initial migraton - users and events tables

Revision ID: 49d7a5a1f8c4
Revises: 
Create Date: 2026-01-23 20:12:34.546948+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49d7a5a1f8c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False, comment='Event id'),
    sa.Column('event_type', sa.String(length=255), nullable=False, comment='Event type (e.g., user.login, api.request)'),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Data Source id'),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Event actual occur time'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When event was ingested into the system'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Event data(flexible json)'),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata'),
    sa.Column('severity', sa.Float(), nullable=False, comment='Severity range 0.0-1.0'),
    sa.Column('anomaly_score', sa.Float(), nullable=True, comment='Anomaly score 0.0-1.0'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix-events-payload-gin', 'events', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('ix-events-severity', 'events', ['severity'], unique=False, postgresql_where=sa.text('severity > 0.7'))
    op.create_index('ix-events-source-time', 'events', ['source_id', 'event_time'], unique=False)
    op.create_index('ix-events-type-time', 'events', ['event_type', 'event_time'], unique=False)
    op.create_index(op.f('ix_events_event_time'), 'events', ['event_time'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_source_id'), 'events', ['source_id'], unique=False)
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True,
               existing_comment='Last login timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False,
               existing_comment='Last login timestamp')
    op.drop_index(op.f('ix_events_source_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_time'), table_name='events')
    op.drop_index('ix-events-type-time', table_name='events')
    op.drop_index('ix-events-source-time', table_name='events')
    op.drop_index('ix-events-severity', table_name='events', postgresql_where=sa.text('severity > 0.7'))
    op.drop_index('ix-events-payload-gin', table_name='events', postgresql_using='gin')
    op.drop_table('events')
    # ### end Alembic commands ###
