"""add_transactions_table

Revision ID: d1ddee0b433c
Revises: fbc702fc02f0
Create Date: 2026-04-30 20:34:56.928729+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1ddee0b433c'
down_revision: Union[str, None] = 'fbc702fc02f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', 'VIEWER', name='user_role'),
               type_=sa.String(length=20),
               existing_comment='User role for permissions',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ADMIN', 'USER', 'VIEWER', name='user_role'),
               existing_comment='User role for permissions',
               existing_nullable=False)
    # ### end Alembic commands ###
