"""Event server default fix

Revision ID: 3d66cf87b961
Revises: 49d7a5a1f8c4
Create Date: 2026-02-03 09:26:09.818130+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d66cf87b961'
down_revision: Union[str, None] = '49d7a5a1f8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='When event was ingested into the system',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='When event was ingested into the system',
               existing_nullable=False)
    # ### end Alembic commands ###
